function btTextSwitch() {
    var x = document.getElementById("history");
    if (x.innerHTML === "<h3>HISTORY</h3><h4>“Battletoads is a beat 'em up/platform video game developed by Rare and published by Tradewest. It is the first installment of the Battletoads series and was originally released on 1 June 1991 for the Nintendo Entertainment System. In the game, three space humanoid toad warriors form a group known as the Battletoads. Two of the Battletoads, Rash and Zitz, embark on a mission to defeat the evil Dark Queen on her planet and rescue their kidnapped friends: Pimple, the third member of the Battletoads, and Princess Angelica.”</h4>") {
      x.innerHTML = "<h3>REASONING</h3><h4>Battletoads is one of the hardest games I have ever played, which ultimately means I never beat it. But just because I did not finish the game though, does not mean I had no fun. Though it can be infuriating, I have fond memories trying over and over to beat the game with friends. Playing it again and again, getting a little bit further each time was awesome feeling. This game also has a ton of style. The art direction, sprites, sounds, and music, all have so much charm that add to the overall experience. Battletoads is definitely one of my favorite beat-em-ups.</h4>";
    } else {
      x.innerHTML = "<h3>HISTORY</h3><h4>“Battletoads is a beat 'em up/platform video game developed by Rare and published by Tradewest. It is the first installment of the Battletoads series and was originally released on 1 June 1991 for the Nintendo Entertainment System. In the game, three space humanoid toad warriors form a group known as the Battletoads. Two of the Battletoads, Rash and Zitz, embark on a mission to defeat the evil Dark Queen on her planet and rescue their kidnapped friends: Pimple, the third member of the Battletoads, and Princess Angelica.”</h4>";
    }
  }

function ihTextSwitch() {
    var x = document.getElementById("history");
    if (x.innerHTML === "<h3>HISTORY</h3><h4>“Ice Hockey is a game that was released on the Nintendo Entertainment System and Famicom Disk System in 1988 and, as the title suggests, is a sports game about ice hockey. It was the first hockey game to be released on a Nintendo gaming system in North America. The game was designed and directed by Hideki Konno.”</h4>") {
      x.innerHTML = "<h3>REASONING</h3><h4>Similar to Tecmo Super Bowl, sports video games of today are often hyper focused on realism and simulation of the legitimate sport, leading it to feel less fun in my opinion. Ice Hockey is the perfect balance of representing the actual sport of hockey and the more lighthearted nature of video games. I have spent hours playing this game with friends, and think it perfectly captures what a sports video game should be. The straightforward controls, simplistic presentation, memorable music and sounds, amusing team builder, and mid-match scuffles that can turn into a button-mashing brawl, make this one of the most fun multiplayer experiences to be had on the NES.</h4>";
    } else {
      x.innerHTML = "<h3>HISTORY</h3><h4>“Ice Hockey is a game that was released on the Nintendo Entertainment System and Famicom Disk System in 1988 and, as the title suggests, is a sports game about ice hockey. It was the first hockey game to be released on a Nintendo gaming system in North America. The game was designed and directed by Hideki Konno.”</h4>";
    }
}

function smbTextSwitch() {
    var x = document.getElementById("history");
    if (x.innerHTML === "<h3>HISTORY</h3><h4>“Super Mario Bros. is a platform game developed and published by Nintendo. It is the successor to the 1983 arcade game Mario Bros. and the first game in the Super Mario series.The NES version received a wide release in North America in 1986. Players control Mario, or his brother Luigi in the multiplayer mode, as they traverse the Mushroom Kingdom to rescue Princess Toadstool from King Koopa (later named Bowser). They traverse side-scrolling stages while avoiding hazards such as enemies and pits with the aid of power-ups such as the Super Mushroom, Fire Flower, and Starman.”</h4>") {
      x.innerHTML = "<h3>REASONING</h3><h4>What hasn’t been said about the original Super Mario Bros.? The video game that essentially saved video games, and became one of the most recognizable characters in the world. For all my gripes I could have with the game, Mario 1 is a classic. The sounds, level design, music, sprites, secrets, make up one of the most important and successful games of all time. But what really got this game on my list was the fond memories I had playing with my Dad. Not to say we didn't bond over anything, but retro video games had been something we both enjoyed and loved just at different times. When I had bought an original NES in the late 2010s, I remember he was just as excited as I was. I had one goal in mind and that was for us to beat the original Super Mario Bros.. My Dad ended up being the one to play and I was a copilot of sorts. I had pulled up a guide to beat the game and it would become something we would try to do every Sunday. It had gotten to a point where we would sort of give up for a period of time, and we would not play for a while. But one Sunday, we booted it up and finally beat the game. It's a different type of feeling to finally beat an old school game, especially on the original hardware. Those memories of playing together is why Super Mario Bros. made the list of my favorite NES games.</h4>";
    } else {
      x.innerHTML = "<h3>HISTORY</h3><h4>“Super Mario Bros. is a platform game developed and published by Nintendo. It is the successor to the 1983 arcade game Mario Bros. and the first game in the Super Mario series.The NES version received a wide release in North America in 1986. Players control Mario, or his brother Luigi in the multiplayer mode, as they traverse the Mushroom Kingdom to rescue Princess Toadstool from King Koopa (later named Bowser). They traverse side-scrolling stages while avoiding hazards such as enemies and pits with the aid of power-ups such as the Super Mushroom, Fire Flower, and Starman.”</h4>";
    }
}

function smb3TextSwitch() {
    var x = document.getElementById("history");
    if (x.innerHTML === "<h3>HISTORY</h3><h4>“Super Mario Bros. 3 (often known as Mario 3, SMB3, or Super Mario 3) is the third game in the Super Mario series. The game was released in 1988, and was developed and published by Nintendo. It was released in Japan on October 23, 1988; in North America on February 9, 1990; and in Europe and Australia on August 29, 1991. Super Mario Bros. 3 has been considered as one of the greatest games of all time. Its complexity and challenging levels made it a huge success.”</h4>") {
      x.innerHTML = "<h3>REASONING</h3><h4>Super Mario Bros. 3 is the definitive Mario experience on the NES. Everything that made the prior Mario games good, was improved upon in the third game. The sprites, music, presentation and controls were all enhanced. Mario 3 also included a hub-like world where you could decide which paths to take or choose to grab a powerup from one of the Toad Houses. This gave more freedom to the player and made it feel more like a modern video game and less of an arcade-styled one. And although multiplayer was not simultaneous, playing 2-player allowed one person to beat a stage so the other would not have to. This made it feel like you were playing together in a sense, instead of what felt like two separate games happening at once like in the original. This was a game I spent forever playing with friends and family. Strategizing the best paths to take, who would do what level and when to grab power ups from toads, made Mario 3 feel like a co-op adventure whenever I played it.</h4>";
    } else {
      x.innerHTML = "<h3>HISTORY</h3><h4>“Super Mario Bros. 3 (often known as Mario 3, SMB3, or Super Mario 3) is the third game in the Super Mario series. The game was released in 1988, and was developed and published by Nintendo. It was released in Japan on October 23, 1988; in North America on February 9, 1990; and in Europe and Australia on August 29, 1991. Super Mario Bros. 3 has been considered as one of the greatest games of all time. Its complexity and challenging levels made it a huge success.”</h4>";
    }
}

function tsbTextSwitch() {
    var x = document.getElementById("history");
    if (x.innerHTML === "<h3>HISTORY</h3><h4>“Tecmo Super Bowl is an American football video game that was released in December 1991. Developed by Tecmo, it is the first sports video game that was licensed by both the National Football League and the National Football League Players Association, thus allowing the game to use both the names and attributes of real NFL teams and real NFL players. Prior games use either the real teams, the real players, or fictional substitutes, but not real teams and real players together.”</h4>") {
      x.innerHTML = "<h3>REASONING</h3><h4>Similar to Ice Hockey, sports video games of today are often hyper focused on realism and simulation of the legitimate sport, leading it to feel less fun in my opinion. Tecmo Super Bowl is the best example of fun over simulation, while still keeping the essence of American Football. Tecmo Super Bowl has a lot more depth than Ice Hockey but still remains a simplistic, arcade-like version of the real sport. With the limited play selection it was always fun trying to guess your opponents choice. The little cutscenes that play during touchdowns, halftimes, or field goal kicks, the randomness of events like fumbles or catches, music, the crunchy block or tackle sounds, make this one of my favorite multiplayer experiences I have ever had in gaming and one of the greatest sports video games.</h4>";
    } else {
      x.innerHTML = "<h3>HISTORY</h3><h4>“Tecmo Super Bowl is an American football video game that was released in December 1991. Developed by Tecmo, it is the first sports video game that was licensed by both the National Football League and the National Football League Players Association, thus allowing the game to use both the names and attributes of real NFL teams and real NFL players. Prior games use either the real teams, the real players, or fictional substitutes, but not real teams and real players together.”</h4>";
    }
}
